"""schema_manifest.yaml → DDL + 知识卡片 + 域索引补丁 的渲染器。

用法（仓库根）：
    python3 scripts/manifest/render.py            # 生成全部产物
    python3 scripts/manifest/render.py --check    # 校验 manifest + 断言产物未被手改（CI 用）

产物（全部带"generated"头，不要手改）：
    database/10_derived.sql                        # CTAS DDL（Postgres，v1 本地库用）
    knowledge/domains/<domain>/<table>.md          # 每表一张数据字典卡片（SQL 转成 Trino）
    knowledge/domains/<domain>/_index.derived.md   # 该域派生表的索引片段
    knowledge/domains/_derived_overview.md         # 派生层总览（L1 路由的补充读物）

## `--check` 校验的是两件事，不是一件

原来 `--check` 只跑 `check(tables)`（manifest 的必填字段/枚举/domain 是否成立），
**从不比对产物**——于是手改一张生成的卡片，它照样打印 `manifest OK` 并 exit 0。
`scripts/test_all.sh` 那一行当时标的是「派生层知识卡片是最新渲染」,名字比它实际
管的多。一个名字比覆盖面大的检查器比没有检查器更坏:它让人以为这块有人看着。
（这是写 L8 负测时抓出来的,见 `scripts/negative_tests.py` 的 `manifest-artifact-handedit`。）

现在 `--check` 两件都做：manifest 自身合法 **且** 上面四类产物与「现在渲染出来的」
逐字相同。改了 manifest 就重新跑一次无参数的 `render.py`，别手改产物。

设计约定：
  - 手写资产（35 基表卡片、mart、域 _index.md）一概不碰；派生表的索引片段
    落在 _index.derived.md，由手写 _index.md 结尾一行链接进去（append_links 打印
    需要人工确认的一次性提示）。
  - deprecated 表的卡片带"⛔ 已废弃"横幅 + replaced_by 指引，索引里同样标注。
    这是噪音表考点的落点：能查到，但读了文档就知道别用。

## 卡片里的 SQL 为什么要转方言

manifest 的 `sql` 写的是 Postgres（`database/10_derived.sql` 和 v1 本地库要它），
但**卡片是给 agent 读的，agent 查的是 Athena（Trino）**。照抄 Postgres 会让 agent
写出跑不了的 SQL——而且没有任何东西会报错，因为文档不会被执行。

所以卡片的「构建口径」节走一遍 `scripts/gen/pg_to_trino.py`。真源仍然只有一份，
只是落地成两种方言。转换结果由 `scripts/lakehouse/verify_doc_sql.py` 拿 Athena 的
EXPLAIN 兜底：卡片里的 SQL 真跑不动，那个脚本会红。
"""
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "gen"))
from pg_to_trino import convert as to_trino  # noqa: E402

try:
    import yaml
except ImportError:
    print("需要 pyyaml：pip install pyyaml（或用 backend/.venv）", file=sys.stderr)
    raise

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "schema_manifest.yaml"
DDL_OUT = ROOT / "database" / "10_derived.sql"
KNOW = ROOT / "knowledge" / "domains"

GEN_MD = "> ⚙️ 本文件由 `scripts/manifest/render.py` 从 `schema_manifest.yaml` 生成，**不要手改**。\n"
GEN_SQL = "-- ⚙️ generated by scripts/manifest/render.py from schema_manifest.yaml — DO NOT EDIT\n"

LAYER_LABEL = {
    "dwd": "DWD 清洗层",
    "dws": "DWS 汇总层",
    "ads": "ADS 应用层",
    "noise": "历史遗留",
}
REQUIRED = ["name", "domain", "layer", "grain", "summary", "use_when", "avoid_when", "sql", "columns"]


def load() -> list[dict]:
    spec = yaml.safe_load(MANIFEST.read_text())
    defaults = spec.get("defaults", {})
    tables = []
    for t in spec["tables"]:
        merged = {**defaults, **t}
        tables.append(merged)
    return tables


def check(tables: list[dict]) -> list[str]:
    errs = []
    seen = set()
    for t in tables:
        name = t.get("name", "<unnamed>")
        for k in REQUIRED:
            if not t.get(k):
                errs.append(f"{name}: 缺少必填字段 {k}")
        if name in seen:
            errs.append(f"{name}: 重名")
        seen.add(name)
        if t.get("layer") not in LAYER_LABEL:
            errs.append(f"{name}: layer 必须是 {list(LAYER_LABEL)} 之一")
        if t.get("layer") == "ads" and not t.get("owner"):
            errs.append(f"{name}: ads 层必须写 owner（口径归属）")
        if t.get("status") == "deprecated" and not t.get("replaced_by"):
            errs.append(f"{name}: deprecated 必须写 replaced_by")
        if not (KNOW / t.get("domain", "")).is_dir():
            errs.append(f"{name}: 未知 domain '{t.get('domain')}'（knowledge/domains/ 下无此目录）")
    return errs


def render_ddl(tables: list[dict]) -> str:
    parts = [GEN_SQL,
             "-- 派生层（DWD/DWS/ADS/噪音）：全部 CTAS，依赖 01-09 已建好、CSV 已灌入。",
             "-- 在 load.sh 中于 09_mart 之后执行。\n"]
    for layer in LAYER_LABEL:
        group = [t for t in tables if t["layer"] == layer]
        if not group:
            continue
        parts.append(f"-- ============ {LAYER_LABEL[layer]} ============\n")
        for t in group:
            sql = t["sql"].strip().rstrip(";")
            parts.append(f"DROP TABLE IF EXISTS {t['name']};")
            parts.append(f"CREATE TABLE {t['name']} AS\n{sql};\n")
    return "\n".join(parts)


def render_card(t: dict) -> str:
    dep = t.get("status") == "deprecated"
    title_note = "（已废弃）" if dep else ""
    lines = [f"# {t['name']} - {t['summary'].split('：')[0]}{title_note}", "", GEN_MD]
    if dep:
        lines += [f"> ⛔ **已废弃，禁止用于新分析**。请改用 `{t['replaced_by']}`。",
                  "> 下文仅供理解这张表为什么存在、以及读到旧查询时如何解读。", ""]
    lines += [f"**层级**：{LAYER_LABEL[t['layer']]}"
              + (f" · **口径归属**：{t['owner']}" if t.get("owner") else ""),
              f"**粒度**：{t['grain']}", "",
              f"{t['summary']}", "",
              "## 何时用这张表", "", f"- ✅ {t['use_when']}", f"- ❌ {t['avoid_when']}", "",
              "## 表结构", "", "| 字段 | 类型 | 说明 |", "|------|------|------|"]
    for c in t["columns"]:
        lines.append(f"| {c['name']} | {c['type']} | {c['desc']} |")
    if t.get("caveats"):
        lines += ["", "## 注意（口径与坑）", ""]
        lines += [f"- {c}" for c in t["caveats"]]
    # 卡片里的 SQL 转成 Trino：agent 照着卡片写 SQL，而 SQL 要交给 Athena 跑
    trino_sql, _ = to_trino(t["sql"].strip().rstrip(";"))
    lines += ["", "## 构建口径（本表如何从基表算出）", "",
              "> 方言为 Trino（Athena）。真源是 `schema_manifest.yaml` 里的 Postgres 写法，",
              "> 由 `scripts/gen/pg_to_trino.py` 转换而来。", "",
              "```sql", trino_sql, "```", ""]
    return "\n".join(lines)


def render_domain_fragment(domain: str, group: list[dict]) -> str:
    lines = [f"# {domain} 域 · 派生层附录", "", GEN_MD,
             "本域除基表外还有以下派生表。**同名近义表怎么选，看「选哪张」列**。", "",
             "| 表名 | 层级 | 一句话 | 选哪张 |", "|------|------|--------|--------|"]
    for t in group:
        dep = t.get("status") == "deprecated"
        pick = f"⛔ 别用，改用 `{t['replaced_by']}`" if dep else t["use_when"]
        lines.append(f"| `{t['name']}`{'（废弃）' if dep else ''} | {LAYER_LABEL[t['layer']]} "
                     f"| {t['summary']} | {pick} |")
    lines += ["", "详情读各表卡片：" + "、".join(f"`{t['name']}.md`" for t in group), ""]
    return "\n".join(lines)


def render_overview(tables: list[dict]) -> str:
    lines = ["# 派生层总览（DWD / DWS / ADS / 历史遗留）", "", GEN_MD,
             "基表之上有一个派生层。**先判断问题该落在哪一层，再进域索引选表**：", "",
             "| 层 | 是什么 | 什么时候用 |", "|----|--------|-----------|",
             "| DWD 清洗层 | 基表的过滤/标准化副本 | 想省掉常规过滤（有效订单、剔匿名）时 |",
             "| DWS 汇总层 | 按主题预聚合，粒度各异 | 问题粒度与表粒度一致时（日/周） |",
             "| ADS 应用层 | 部门口径表，**口径互不相同** | 问题点名口径（财务/增长）时 |",
             "| 历史遗留 | 备份/临时表，**已废弃** | 永远别用；读到旧查询时用于解读 |", "",
             "## 全部派生表", "",
             "| 表 | 域 | 层 | 状态 |", "|----|----|----|------|"]
    for t in tables:
        lines.append(f"| `{t['name']}` | {t['domain']} | {LAYER_LABEL[t['layer']]} "
                     f"| {'⛔ 废弃' if t.get('status') == 'deprecated' else 'active'} |")
    lines += ["", "> 口径冲突的裁决顺序：**call_metric（治理指标）> mart/ADS 卡片写明的口径 > 自己现推**。", ""]
    return "\n".join(lines)


def artifacts(tables: list[dict]) -> dict[Path, str]:
    """全部产物 → 内容。渲染与落盘分开，`--check` 才有东西可比。"""
    out: dict[Path, str] = {DDL_OUT: render_ddl(tables)}
    by_domain: dict[str, list[dict]] = {}
    for t in tables:
        by_domain.setdefault(t["domain"], []).append(t)
        out[KNOW / t["domain"] / f"{t['name']}.md"] = render_card(t)
    for domain, group in by_domain.items():
        out[KNOW / domain / "_index.derived.md"] = render_domain_fragment(domain, group)
    out[KNOW / "_derived_overview.md"] = render_overview(tables)
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="只校验：manifest 合法 + 产物与现在渲染的逐字相同")
    args = ap.parse_args()

    tables = load()
    errs = check(tables)
    if errs:
        print("manifest 校验失败：")
        for e in errs:
            print("  -", e)
        return 1
    print(f"manifest OK：{len(tables)} 张派生表")

    want = artifacts(tables)

    if args.check:
        drift: list[tuple[Path, str]] = []
        for path, text in sorted(want.items()):
            if not path.exists():
                drift.append((path, "文件不存在"))
            elif path.read_text(encoding="utf-8") != text:
                have = path.read_text(encoding="utf-8").splitlines()
                d = [x for x in difflib.unified_diff(have, text.splitlines(),
                                                     lineterm="", n=0)
                     if x[:1] in "+-" and x[:3] not in ("---", "+++")]
                drift.append((path, f"{len(d)} 行与真源不同：" +
                              "; ".join(x.strip()[:60] for x in d[:3])))
        if drift:
            print(f"\n产物漂移 {len(drift)} 个文件 ❌（它们是生成物，不该手改）\n")
            for path, why in drift:
                print(f"  - {path.relative_to(ROOT)}：{why}")
            print("\n改法：把改动写回 schema_manifest.yaml，再跑一次 "
                  "`python3 scripts/manifest/render.py`。")
            return 1
        print(f"生成物一致 ✅  {len(want)} 个文件与 manifest 渲染结果逐字相同")
        return 0

    for path, text in sorted(want.items()):
        path.write_text(text)
        print(f"→ {path.relative_to(ROOT)}")

    # 手写索引需要的一次性接线提示（不自动改手写文件）
    print("\n接线检查（手写文件里应有以下链接，缺了要补）：")
    print("  knowledge/domains/_index.md → _derived_overview.md")
    for domain in sorted({t["domain"] for t in tables}):
        print(f"  knowledge/domains/{domain}/_index.md → _index.derived.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
