"""schema_manifest.yaml → DDL + 知识卡片 + 域索引补丁 的渲染器。

用法（仓库根）：
    python3 scripts/manifest/render.py            # 生成全部产物
    python3 scripts/manifest/render.py --check    # 只校验 manifest（CI 用）

产物（全部带"generated"头，不要手改）：
    database/10_derived.sql                        # CTAS DDL，按 layer 分节
    knowledge/domains/<domain>/<table>.md          # 每表一张数据字典卡片
    knowledge/domains/<domain>/_index.derived.md   # 该域派生表的索引片段
    knowledge/domains/_derived_overview.md         # 派生层总览（L1 路由的补充读物）

设计约定：
  - 手写资产（35 基表卡片、mart、域 _index.md）一概不碰；派生表的索引片段
    落在 _index.derived.md，由手写 _index.md 结尾一行链接进去（append_links 打印
    需要人工确认的一次性提示）。
  - deprecated 表的卡片带"⛔ 已废弃"横幅 + replaced_by 指引，索引里同样标注。
    这是噪音表考点的落点：能查到，但读了文档就知道别用。
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("需要 pyyaml：pip install pyyaml（或用 backend/.venv）", file=sys.stderr)
    raise

ROOT = Path(__file__).resolve().parents[2]
MANIFEST = ROOT / "schema_manifest.yaml"
DDL_OUT = ROOT / "database" / "10_derived.sql"
KNOW = ROOT / "knowledge" / "domains"

GEN_MD = "> ⚙️ 本文件由 `scripts/manifest/render.py` 从 `schema_manifest.yaml` 生成，**不要手改**。\n"
GEN_SQL = "-- ⚙️ generated by scripts/manifest/render.py from schema_manifest.yaml — DO NOT EDIT\n"

LAYER_LABEL = {
    "dwd": "DWD 清洗层",
    "dws": "DWS 汇总层",
    "ads": "ADS 应用层",
    "noise": "历史遗留",
}
REQUIRED = ["name", "domain", "layer", "grain", "summary", "use_when", "avoid_when", "sql", "columns"]


def load() -> list[dict]:
    spec = yaml.safe_load(MANIFEST.read_text())
    defaults = spec.get("defaults", {})
    tables = []
    for t in spec["tables"]:
        merged = {**defaults, **t}
        tables.append(merged)
    return tables


def check(tables: list[dict]) -> list[str]:
    errs = []
    seen = set()
    for t in tables:
        name = t.get("name", "<unnamed>")
        for k in REQUIRED:
            if not t.get(k):
                errs.append(f"{name}: 缺少必填字段 {k}")
        if name in seen:
            errs.append(f"{name}: 重名")
        seen.add(name)
        if t.get("layer") not in LAYER_LABEL:
            errs.append(f"{name}: layer 必须是 {list(LAYER_LABEL)} 之一")
        if t.get("layer") == "ads" and not t.get("owner"):
            errs.append(f"{name}: ads 层必须写 owner（口径归属）")
        if t.get("status") == "deprecated" and not t.get("replaced_by"):
            errs.append(f"{name}: deprecated 必须写 replaced_by")
        if not (KNOW / t.get("domain", "")).is_dir():
            errs.append(f"{name}: 未知 domain '{t.get('domain')}'（knowledge/domains/ 下无此目录）")
    return errs


def render_ddl(tables: list[dict]) -> str:
    parts = [GEN_SQL,
             "-- 派生层（DWD/DWS/ADS/噪音）：全部 CTAS，依赖 01-09 已建好、CSV 已灌入。",
             "-- 在 load.sh 中于 09_mart 之后执行。\n"]
    for layer in LAYER_LABEL:
        group = [t for t in tables if t["layer"] == layer]
        if not group:
            continue
        parts.append(f"-- ============ {LAYER_LABEL[layer]} ============\n")
        for t in group:
            sql = t["sql"].strip().rstrip(";")
            parts.append(f"DROP TABLE IF EXISTS {t['name']};")
            parts.append(f"CREATE TABLE {t['name']} AS\n{sql};\n")
    return "\n".join(parts)


def render_card(t: dict) -> str:
    dep = t.get("status") == "deprecated"
    title_note = "（已废弃）" if dep else ""
    lines = [f"# {t['name']} - {t['summary'].split('：')[0]}{title_note}", "", GEN_MD]
    if dep:
        lines += [f"> ⛔ **已废弃，禁止用于新分析**。请改用 `{t['replaced_by']}`。",
                  "> 下文仅供理解这张表为什么存在、以及读到旧查询时如何解读。", ""]
    lines += [f"**层级**：{LAYER_LABEL[t['layer']]}"
              + (f" · **口径归属**：{t['owner']}" if t.get("owner") else ""),
              f"**粒度**：{t['grain']}", "",
              f"{t['summary']}", "",
              "## 何时用这张表", "", f"- ✅ {t['use_when']}", f"- ❌ {t['avoid_when']}", "",
              "## 表结构", "", "| 字段 | 类型 | 说明 |", "|------|------|------|"]
    for c in t["columns"]:
        lines.append(f"| {c['name']} | {c['type']} | {c['desc']} |")
    if t.get("caveats"):
        lines += ["", "## 注意（口径与坑）", ""]
        lines += [f"- {c}" for c in t["caveats"]]
    lines += ["", "## 构建口径（本表如何从基表算出）", "",
              "```sql", t["sql"].strip().rstrip(";"), "```", ""]
    return "\n".join(lines)


def render_domain_fragment(domain: str, group: list[dict]) -> str:
    lines = [f"# {domain} 域 · 派生层附录", "", GEN_MD,
             "本域除基表外还有以下派生表。**同名近义表怎么选，看「选哪张」列**。", "",
             "| 表名 | 层级 | 一句话 | 选哪张 |", "|------|------|--------|--------|"]
    for t in group:
        dep = t.get("status") == "deprecated"
        pick = f"⛔ 别用，改用 `{t['replaced_by']}`" if dep else t["use_when"]
        lines.append(f"| `{t['name']}`{'（废弃）' if dep else ''} | {LAYER_LABEL[t['layer']]} "
                     f"| {t['summary']} | {pick} |")
    lines += ["", "详情读各表卡片：" + "、".join(f"`{t['name']}.md`" for t in group), ""]
    return "\n".join(lines)


def render_overview(tables: list[dict]) -> str:
    lines = ["# 派生层总览（DWD / DWS / ADS / 历史遗留）", "", GEN_MD,
             "基表之上有一个派生层。**先判断问题该落在哪一层，再进域索引选表**：", "",
             "| 层 | 是什么 | 什么时候用 |", "|----|--------|-----------|",
             "| DWD 清洗层 | 基表的过滤/标准化副本 | 想省掉常规过滤（有效订单、剔匿名）时 |",
             "| DWS 汇总层 | 按主题预聚合，粒度各异 | 问题粒度与表粒度一致时（日/周） |",
             "| ADS 应用层 | 部门口径表，**口径互不相同** | 问题点名口径（财务/增长）时 |",
             "| 历史遗留 | 备份/临时表，**已废弃** | 永远别用；读到旧查询时用于解读 |", "",
             "## 全部派生表", "",
             "| 表 | 域 | 层 | 状态 |", "|----|----|----|------|"]
    for t in tables:
        lines.append(f"| `{t['name']}` | {t['domain']} | {LAYER_LABEL[t['layer']]} "
                     f"| {'⛔ 废弃' if t.get('status') == 'deprecated' else 'active'} |")
    lines += ["", "> 口径冲突的裁决顺序：**call_metric（治理指标）> mart/ADS 卡片写明的口径 > 自己现推**。", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="只校验不写文件")
    args = ap.parse_args()

    tables = load()
    errs = check(tables)
    if errs:
        print("manifest 校验失败：")
        for e in errs:
            print("  -", e)
        return 1
    print(f"manifest OK：{len(tables)} 张派生表")
    if args.check:
        return 0

    DDL_OUT.write_text(render_ddl(tables))
    print(f"→ {DDL_OUT.relative_to(ROOT)}")

    by_domain: dict[str, list[dict]] = {}
    for t in tables:
        by_domain.setdefault(t["domain"], []).append(t)
        card = KNOW / t["domain"] / f"{t['name']}.md"
        card.write_text(render_card(t))
        print(f"→ {card.relative_to(ROOT)}")
    for domain, group in by_domain.items():
        frag = KNOW / domain / "_index.derived.md"
        frag.write_text(render_domain_fragment(domain, group))
        print(f"→ {frag.relative_to(ROOT)}")
    over = KNOW / "_derived_overview.md"
    over.write_text(render_overview(tables))
    print(f"→ {over.relative_to(ROOT)}")

    # 手写索引需要的一次性接线提示（不自动改手写文件）
    print("\n接线检查（手写文件里应有以下链接，缺了要补）：")
    print("  knowledge/domains/_index.md → _derived_overview.md")
    for domain in by_domain:
        print(f"  knowledge/domains/{domain}/_index.md → _index.derived.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
