-- ⚙️ generated by scripts/manifest/render.py from schema_manifest.yaml — DO NOT EDIT

-- 派生层（DWD/DWS/ADS/噪音）：全部 CTAS，依赖 01-09 已建好、CSV 已灌入。
-- 在 load.sh 中于 09_mart 之后执行。

-- ============ DWD 清洗层 ============

DROP TABLE IF EXISTS dwd_orders_valid;
CREATE TABLE dwd_orders_valid AS
SELECT order_id, order_no, user_id, status,
       total_amount, discount_amount, shipping_fee, actual_amount,
       item_count, coupon_id, placed_at, paid_at
FROM orders
WHERE status IN ('paid','shipped','delivered');

DROP TABLE IF EXISTS dwd_events_app;
CREATE TABLE dwd_events_app AS
SELECT event_id, user_id, session_id, event_name, event_time, page_name
FROM events
WHERE user_id IS NOT NULL;

-- ============ DWS 汇总层 ============

DROP TABLE IF EXISTS dws_user_daily;
CREATE TABLE dws_user_daily AS
WITH ev AS (
  SELECT user_id, event_time::date AS dt,
         count(*) AS event_cnt, count(DISTINCT session_id) AS session_cnt
  FROM events WHERE user_id IS NOT NULL GROUP BY 1, 2
),
od AS (
  SELECT user_id, placed_at::date AS dt,
         count(*) AS order_cnt,
         sum(actual_amount) FILTER (WHERE status IN ('paid','shipped','delivered')) AS paid_amount
  FROM orders GROUP BY 1, 2
)
SELECT COALESCE(ev.user_id, od.user_id) AS user_id,
       COALESCE(ev.dt, od.dt)           AS dt,
       COALESCE(ev.event_cnt, 0)        AS event_cnt,
       COALESCE(ev.session_cnt, 0)      AS session_cnt,
       COALESCE(od.order_cnt, 0)        AS order_cnt,
       COALESCE(od.paid_amount, 0)::numeric(14,2) AS paid_amount
FROM ev FULL OUTER JOIN od ON ev.user_id = od.user_id AND ev.dt = od.dt;

DROP TABLE IF EXISTS dws_channel_weekly;
CREATE TABLE dws_channel_weekly AS
SELECT c.channel_id, c.channel_name,
       date_trunc('week', d.date)::date AS week_start,
       sum(d.cost)::numeric(14,2)  AS cost,
       sum(d.installs)             AS installs,
       count(DISTINCT ua.user_id)  AS new_users,
       (sum(d.cost) / NULLIF(count(DISTINCT ua.user_id), 0))::numeric(12,2) AS weekly_cac
FROM channel_daily_costs d
JOIN channels c USING (channel_id)
LEFT JOIN user_attributions ua
  ON ua.channel_id = d.channel_id
 AND ua.attribution_type = 'last_touch'
 AND ua.attributed_at::date >= date_trunc('week', d.date)::date
 AND ua.attributed_at::date <  date_trunc('week', d.date)::date + 7
GROUP BY 1, 2, 3;

-- ============ ADS 应用层 ============

DROP TABLE IF EXISTS fin_daily_revenue;
CREATE TABLE fin_daily_revenue AS
WITH paid AS (
  SELECT paid_at::date AS dt,
         sum(actual_amount - shipping_fee) AS gross_revenue
  FROM orders
  WHERE status IN ('paid','shipped','delivered') AND paid_at IS NOT NULL
  GROUP BY 1
),
refunds AS (
  SELECT refunded_at::date AS dt, sum(actual_amount) AS refund_amount
  FROM orders WHERE status = 'refunded' AND refunded_at IS NOT NULL
  GROUP BY 1
)
SELECT COALESCE(p.dt, r.dt) AS dt,
       COALESCE(p.gross_revenue, 0)::numeric(14,2) AS gross_revenue,
       COALESCE(r.refund_amount, 0)::numeric(14,2) AS refund_amount,
       (COALESCE(p.gross_revenue, 0) - COALESCE(r.refund_amount, 0))::numeric(14,2) AS net_revenue
FROM paid p FULL OUTER JOIN refunds r USING (dt);

DROP TABLE IF EXISTS growth_daily_gmv;
CREATE TABLE growth_daily_gmv AS
SELECT placed_at::date AS dt,
       sum(actual_amount) FILTER (WHERE status IN ('paid','shipped','delivered'))::numeric(14,2) AS gmv,
       count(*) FILTER (WHERE status IN ('paid','shipped','delivered'))          AS paid_orders,
       count(DISTINCT user_id) FILTER (WHERE status IN ('paid','shipped','delivered')) AS paying_users,
       count(*) AS all_orders
FROM orders
GROUP BY 1;

-- ============ 历史遗留 ============

DROP TABLE IF EXISTS orders_backup_20251201;
CREATE TABLE orders_backup_20251201 AS
SELECT order_id, order_no, user_id, status,
       total_amount, actual_amount, placed_at
FROM orders
WHERE placed_at < DATE '2025-12-01';

DROP TABLE IF EXISTS tmp_campaign_roi_analysis;
CREATE TABLE tmp_campaign_roi_analysis AS
SELECT c.channel_id, c.channel_name,
       sum(d.cost)::numeric(14,2) AS total_cost,
       NULL::numeric(14,2)        AS attributed_gmv,
       NULL::numeric(8,4)         AS roi
FROM channel_daily_costs d JOIN channels c USING (channel_id)
WHERE d.date < DATE '2026-01-10'
GROUP BY 1, 2;
